compile:
	g++ -o programa HatCreator.cpp header/FileHeader.cpp imageBody/Body.cpp encrypt/VigenereCipher.cpp encrypt/main_vigenerecipher.cpp compress/LZW.cpp -std=c++11 -Wall -Wextra `pkg-config --cflags --libs opencv4`
run:
	./programa
